### ISSUE TITLE
Interface Incompatibility

### ISSUE THREAD

**Issue by cl0ud-o** [gridsome/gridsome.org#226] opened 2019-08-02 16:20 UTC
## Description

If anyone use(usually most people) dark mode on web browser and visit to gridsome homepage and other pages then good luck .

### Steps to reproduce

Install darkreader extension for example. (available for most browsers)
 Google Chrome - https://chrome.google.com/webstore/detail/dark-reader/eimadpbcbfnmbkopoojfekhnkhdbieeh

Now visit to Gridsome pages

### Expected result

Even incompatible but shouldn't worst like that. Atleast readable interface expected.

### Actual result

Become too darker with replaced black, transparent colors and difficult read or see most contents

![image](https://user-images.githubusercontent.com/51697989/62384039-8ea08480-b57b-11e9-9a81-fe036547faec.png)

![image](https://user-images.githubusercontent.com/51697989/62384078-9d873700-b57b-11e9-8d2b-83dae4963c64.png)

**Comment by 12vanblart** [comment] 2019-08-08 16:59
I installed Dark Reader and poked around a bit, but it looks like an issue with Dark Reader not processing `background: linear-gradient`. 

I'd recommend checking their repo and see if there's an issue for this and submit one if not.

**Comment by Cloud-O** [comment] 2019-08-10 04:37
Well, that's likely 1/10000 issue. Someone else familiar with dark reader (or other extensions that process similar to display dark web pages) Personally i'm not sure if i have seen such as worst while browser websites for years

@12vanblart 
> I'd recommend checking their repo and see if there's an issue for this and submit one if not.there See there you can do ;) https://github.com/darkreader/darkreader

**Comment by Erbenos** [comment] 2019-12-11 21:23
Can we close this issue? This is caused by extension and not the project itself. Now it's even less relevant since the website itself implements dark mode.

**Closed** 2020-03-07 21:51 UTC
